const colors={Applications:'#b892ff',Documents:'#58a6ff',Images:'#ff8b93',Videos:'#ffb95e',Audio:'#45d3a3',Archives:'#dbcf63',Code:'#59c7e8',Temporary:'#a5aebb',Other:'#6b7280',Folders:'#58a6ff'};
const icons={Applications:'⬡',Documents:'▤',Images:'▧',Videos:'▶',Audio:'♪',Archives:'▣',Code:'⌘',Temporary:'⌫',Other:'◇',Folders:'▰'};
const state={files:[],folders:[],categories:{},capacity:{total:0,used:0,free:0},root:'',view:'all',category:'All',query:'',selected:null,scanning:false};
const $=id=>document.getElementById(id);
const bridge=command=>window.webkit?.messageHandlers?.spacelens?.postMessage(JSON.stringify(typeof command==='string'?{command}:command));
function size(bytes){if(!Number.isFinite(bytes))return '—';const units=['B','KB','MB','GB','TB'];let n=bytes,u=0;while(n>=1024&&u<units.length-1){n/=1024;u++}return `${n.toFixed(u===0?0:n>=100?0:n>=10?1:2)} ${units[u]}`}
function shortPath(path){if(!path)return '';return path.replace(/^\/home\/[^/]+/,'~')}
function toast(message){const el=$('toast');el.textContent=message;el.classList.add('visible');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('visible'),2200)}
function renderCategories(){const nav=$('categoryNav');nav.innerHTML='';Object.keys(colors).filter(x=>x!=='Folders').forEach(category=>{const button=document.createElement('button');button.className=`nav-item ${state.category===category?'selected':''}`;button.innerHTML=`<span class="cat-dot" style="background:${colors[category]}"></span>${category}<span class="nav-size">${size(state.categories[category]||0)}</span>`;button.onclick=()=>{state.category=state.category===category?'All':category;state.view='all';render()};nav.append(button)})}
function renderStorage(){const c=state.capacity,total=Math.max(c.total,1),used=c.used||0;$('usedSize').textContent=size(used);$('totalSize').textContent=size(c.total);$('freeSize').textContent=`${size(c.free)} available`;$('orbitValue').textContent=size(c.free);$('percentFull').textContent=`${Math.round(used/total*100)}% full`;$('rootPath').textContent=`⌁   ${shortPath(state.root)||'Home folder'}`;const bar=$('storageBar');bar.innerHTML='';Object.entries(state.categories).filter(([,value])=>value>0).sort((a,b)=>b[1]-a[1]).forEach(([category,value])=>{const part=document.createElement('i');part.style.width=`${Math.max(value/total*100,.5)}%`;part.style.background=colors[category]||colors.Other;part.title=`${category}: ${size(value)}`;bar.append(part)});const free=document.createElement('i');free.className='bar-empty';bar.append(free)}
function currentItems(){let items=state.view==='folders'?state.folders:state.files;if(state.category!=='All'&&state.view!=='folders')items=items.filter(item=>item.category===state.category);if(state.query){const q=state.query.toLowerCase();items=items.filter(item=>`${item.name} ${item.path}`.toLowerCase().includes(q))}return items}
function renderTable(){const items=currentItems();$('viewTitle').textContent=state.view==='folders'?'Largest folders':state.category==='All'?'Largest files':state.category;$('itemSummary').textContent=`${items.length.toLocaleString()} shown · sorted by size`;$('emptyState').classList.toggle('visible',!items.length);const rows=$('fileRows');rows.innerHTML='';items.forEach(item=>{const row=document.createElement('tr');row.tabIndex=0;row.className=state.selected?.path===item.path?'selected':'';row.innerHTML=`<td><div class="file-cell"><span class="file-icon" style="color:${colors[item.category]||colors.Other};background:${colors[item.category]||colors.Other}16">${icons[item.category]||icons.Other}</span><span class="file-copy"><strong title="${escapeHtml(item.name)}">${escapeHtml(item.name)}</strong><small>${escapeHtml(item.kind)}</small></span></div></td><td title="${escapeHtml(item.path)}">${escapeHtml(shortPath(item.path))}</td><td>${escapeHtml(item.modified)}</td><td class="number size">${size(item.size)}</td><td><button class="open-button" title="Open containing folder">↗</button></td>`;row.onclick=e=>{if(e.target.closest('.open-button')){bridge({command:'open-path',path:item.path});toast('Opened containing folder');return}state.selected=item;renderTable();renderDetails()};row.onkeydown=e=>{if(e.key==='Enter'){state.selected=item;renderTable();renderDetails()}};rows.append(row);if(!state.selected)state.selected=item})}
function escapeHtml(value){return String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderDetails(){const item=state.selected,panel=$('detailPanel');if(!item){panel.innerHTML='<div class="empty-detail"><span>▧</span><strong>Select an item</strong><small>Choose a file or folder to inspect.</small></div>';return}const percent=state.capacity.used?item.size/state.capacity.used*100:0;panel.innerHTML=`<div class="detail-icon" style="--detail-color:${colors[item.category]||colors.Other}">${icons[item.category]||icons.Other}</div><p class="detail-kicker">SELECTED ITEM</p><h2>${escapeHtml(item.name)}</h2><p class="detail-path">${escapeHtml(shortPath(item.path))}</p><div class="detail-size"><strong>${size(item.size)}</strong><small>${percent.toFixed(percent<.1?2:1)}% of used disk space</small></div><dl><div><dt>Kind</dt><dd>${escapeHtml(item.kind)}</dd></div><div><dt>Category</dt><dd>${escapeHtml(item.category)}</dd></div><div><dt>Modified</dt><dd>${escapeHtml(item.modified)}</dd></div></dl><button id="openSelected" class="button">Open containing folder &nbsp;↗</button>`;$('openSelected').onclick=()=>bridge({command:'open-path',path:item.path})}
function render(){renderCategories();renderStorage();renderTable();renderDetails();document.querySelectorAll('[data-view]').forEach(button=>{button.classList.toggle('active',button.dataset.view===state.view);button.classList.toggle('selected',false)})}
function setScanning(scanning){state.scanning=scanning;$('scanProgress').classList.toggle('visible',scanning);$('scanStatus').classList.toggle('working',scanning)}
window.SpaceLens={receive(message){const {event,payload}=message;if(event==='scan-start'){state.root=payload.root;state.selected=null;setScanning(true);$('scanStatus').lastElementChild.textContent=`Scanning ${shortPath(payload.root)}`;$('progressTitle').textContent='Scanning disk contents';$('progressDetail').textContent=shortPath(payload.root);renderStorage()}else if(event==='scan-progress'){$('progressDetail').textContent=`${payload.files.toLocaleString()} files · ${size(payload.bytes)} checked · ${shortPath(payload.current)}`;$('fileCount').textContent=payload.files.toLocaleString();$('folderCount').textContent=payload.folders.toLocaleString()}else if(event==='scan-complete'){Object.assign(state,payload);state.selected=payload.files[0]||payload.folders[0]||null;setScanning(false);$('scanStatus').lastElementChild.textContent=`Scan complete · ${new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}`;$('fileCount').textContent=payload.fileCount.toLocaleString();$('folderCount').textContent=payload.folderCount.toLocaleString();$('reclaimSize').textContent=size(payload.categories.Temporary||0);$('errorCount').textContent=payload.errors.toLocaleString();render()}else if(event==='cancelled'){setScanning(false);$('scanStatus').lastElementChild.textContent='Scan cancelled';toast('Scan cancelled')}else if(event==='scan-error'){setScanning(false);toast(payload.message)}}};
document.querySelectorAll('[data-command]').forEach(button=>button.onclick=()=>bridge(button.dataset.command));document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{state.view=button.dataset.view;state.category='All';state.selected=null;render()});$('searchInput').oninput=e=>{state.query=e.target.value;renderTable()};bridge('ready');
